[package]
name = "jsonata"
version = "0.1.0"
authors = ["Johan Venter <johan.venter@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
json = "0.12"
structopt = "0.3"

[dev-dependencies]
test-case = "1.2.0"
test-generator = "0.3"
