[package]
name = "jsonata"
version = "0.1.0"
authors = ["Johan Venter <johan.venter@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.11"
json = "0.12.4"

[dev-dependencies]
test-case = "1.0.0"
