[package]
name = "jsonata-signature-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
jsonata-signatures = { path = "../jsonata-signatures" }

syn = "1.0.85"
quote = "1.0.14"

