[package]
name = "jsonata-wasm"
version = "0.1.0"
authors = ["Johan Venter <johan.venter@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
jsonata = { path = "../jsonata" }

wasm-bindgen = "0.2.78"