[package]
name = "jsonata-signatures"
version = "0.1.0"
authors = ["Johan Venter <johan.venter@gmail.com>"]
edition = "2021"

[dependencies]
jsonata-errors = { path = "../jsonata-errors" }

bitflags = "1.3.2"